config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
                     omniauth_callbacks: 'users/omniauth_callbacks',
                     registrations: 'users/registrations' }
  resources :users
  resources :posts do
    resources :comments
  end   

  get '/users/:user_id/friends', to: 'users#friends_index', as: 'user_friends'
  post 'posts/add_like/:id', to: 'posts#add_like', as: 'post_add_like'
  post 'users/request_friend/:id', to: 'users#request_friend', as: 'request_friend'
  post 'users/accept_friend/:id', to: 'users#accept_friend', as: 'accept_friend'
  post 'friendships/destroy/:id', to: 'friendships#destroy', as: 'destroy_friendship'
  post 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord

  
  has_many :posts
  has_many :comments
  has_many :post_likes
  has_many :liked_posts, :through => :post_likes, :source => :post
  has_many :friendships, :foreign_key => :accepting_friend_id
  has_many :friendships, :foreign_key => :inviting_friend_id 

  has_and_belongs_to_many :invited_friends,
                class_name: 'User',
                join_table: :friendships,
                foreign_key: :inviting_friend_id,
                association_foreign_key: :accepting_friend_id


  has_and_belongs_to_many :accepted_friends,
                class_name: 'User',
                join_table: :friendships,
                foreign_key: :accepting_friend_id,
                association_foreign_key: :inviting_friend_id              
  
                 
  def pending_invite_friends
    (invited_friends.joins(:friendships).merge(Friendship.pending))
  end

  def confirmed_invite_friends
    (invited_friends.joins(:friendships).merge(Friendship.accepted))
  end

  def pending_accept_friends
    (accepted_friends.joins(:friendships).merge(Friendship.pending))
  end

  def confirmed_accept_friends
    (accepted_friends.joins(:friendships).merge(Friendship.accepted))
  end

  def friends
    (confirmed_invite_friends + confirmed_accept_friends).flatten.uniq
  end

  def feed
    (self.friends << self)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
      
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session["devise.facebook.data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    # disabling mailer pending sendgrid addon
    # UserMailer.welcome_email(resource).deliver unless resource.invalid?
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
    @user = User.find(params[:id])
  end

  def index
    @search = params['search']
    if @search.present?
      @users = User.where('name = ?', @search['name'])
    else
      @users = (User.all.excluding(current_user.friends, current_user))
    end
  end

  def friends_index
    @user = User.find(params[:user_id])
    @friends = @user.friends 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update((user_params))
    redirect_to user_path(@user)
  end

  def request_friend
    @friend = User.find(params[:id])
    @request = Friendship.new
    @request.status = 'pending'
    @request.inviter = current_user
    @request.accepter = @friend
    @request.save
    redirect_to root_path
  end

  def accept_friend
    @request = Friendship.find(params[:id])
    @request.status = 'accepted'
    @request.save
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :location, :birthday, :company)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_feed.html.erb
<div class='level'>
</div>
<div class='columns'>
  <div class='column is-one-quarter'>
    <div class='field'>
      <div class='control'>
      <%= form_with url: users_path, method: :get do |f| %>
        <%= f.label name='search[name]', 'search for users by name', class: 'label has-text-white' %>
        <%= f.text_field name ='search[name]', class: 'input' %>
      </div>
    </div>
    <div class='field is-horizontal'>
      <div class='control'>    
        <%= f.submit 'search', class: 'button is-black has-text-success'%>
      <% end %>
      </div>
      <div class='control'>
        <%= button_to 'see all', users_path, method: :get, class: 'button is-success has-text-black' %>
      </div>
    </div>
  </div>
</div>  
<div class='columns is-multiline'>  
<% if @users.empty? %>
  <div class='column is-one-quarter'>
    <div class='card has-background-warning'>
      <div class='card-header'>
        <p class='card-header-title has-text-danger'>
        no users to show
        </p>
      </div>
    </div>
  </div>  
<% end %>
  <% @users.each do |u| %>
  <div class='column is-one-quarter'>  
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(u) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(u.email, size: 64, alt: u.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= u.name %>
        </p>
      <% end %>
      </div>  
      <div class='card-footer'>
        <% if u.friendships.pending.by_accepter(current_user).first.present? %>
        <div class='card-footer-item'>
          <%= button_to 'accept', accept_friend_path(u.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-success' %>
          <%= button_to 'reject', destroy_friendship_path(u.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-danger' %>
        </div>
        <% elsif current_user.friendships.pending.by_accepter(u).first.present? %>  
        <div class='card-footer-item'>
          <button class='button is-static'>invited</button>
        </div>
        <% else %>
        <div class='card-footer-item'>  
          <%= button_to 'add friend', request_friend_path(u), method: :post, class: 'button is-info' %>
        </div>  
        <% end %>  
      </div>  
    </div>
  </div>
  <% end %>
</div>  

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <div class='field'>
    <div class='control'>
    <%= f.input :name,
                autofocus: true,
                input_html: { class: 'input' },
                wrapper: false,
                label: false,
                placeholder: 'name' %>
                
    </div>
  </div>    
  <div class='field'>
    <div class='control'>
    <%= f.input :bio,
                input_html: { class: 'textarea ' },
                wrapper: false,
                label: false,
                placeholder: 'bio'  %>
    </div>
  </div>  
  <div class='field'>
    <div class='control'>
    <%= f.input :location,
                autofocus: true,
                input_html: { class: 'input' },
                wrapper: false,
                label: false,
                placeholder: 'location' %>
                
    </div>
  </div>
  <div class='field'>
    <div class='control'>
    <%= f.input :company,
                autofocus: true,
                input_html: { class: 'input' },
                wrapper: false,
                label: false,
                placeholder: 'company' %>
                
    </div>
  </div>
  <div class='field'>
    <div class='control'>
    <%= f.input :birthday,
                autofocus: true,
                input_html: { class: 'date' },
                start_year: Date.today.year - 125,
                wrapper: false,
                label: false,
                placeholder: 'birthday' %>
                
    </div>
  </div>
  <div class='field'>
    <div class='control'>  
    <%= f.button :submit, "update", class: 'button is-primary' %>
    </div>
  </div>  
<% end %>

app/views/users/_left.html.erb
<aside class='menu has-background-black has-text-white px-5'>
  <p class='menu-label'>
  <%= @user.name %>'s profile
  </p>
  <div class='card has-background-black has-text-white'>
    <div class='card-header'>
      <p class='title is-5 has-text-success'>about me:</p>
    </div>
    <div class='card-content'>
      <p><%= @user.bio %></p>
    </div>
    <div class='card-header'>
      <p class='title is-5 has-text-success'>location:</p>
    </div>
    <div class='card-content'>
      <p><%= @user.location %></p>
    </div>
    <div class='card-header'>
      <p class='title is-5 has-text-success'>works at:</p>
    </div>
    <div class='card-content'>
      <p><%= @user.company %></p>
    </div>
    <div class='card-header'>
      <p class='title is-5 has-text-success'>birthday:</p>
    </div>
    <div class='card-content'>
      <p><%= @user.birthday %></p>
    </div>
    <div class='card-header'>
      <p class='title is-5 has-text-success'><%= @user.name%>'s friends:</p>
    </div>
    <div class='card-content'>
      <%= link_to user_friends_path(@user), class: 'has-text-success' do %>
      <p><%= @user.friends.count %> friends</p>
      <% end %>
    </div>    
    <% if @user == current_user %>
    <div class='card-footer'>
      <div class='card-footer-item'>
        <%= link_to 'edit profile', edit_user_path(@user), class: 'has-text-info' %>
      </div>
    </div>
    <% end %>    
  </div>
</aside> 
<div class='level'>
</div>
<% if @user == current_user %>
  <%= render 'pending' %>
<% end %>  

app/views/users/_pending.html.erb
<% if user_signed_in? %>
<aside class='menu has-background-black has-text-white'>
  <p class='menu-label'>pending friend requests
  </p>
  <% if current_user.pending_invite_friends.empty? && current_user.pending_accept_friends.empty? %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
        <p class='card-header-title'>
        no new friend requests
        </p>
      </div>
    </div>    
  <% end %>
  <% current_user.pending_accept_friends.uniq.each do |f| %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(f) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(f.email, size: 64, alt: f.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= f.name %>
        </p>
      </div>
      <% end %>  
      <div class='card-footer'>
        <div class='card-footer-item'>
          <%= button_to 'accept', accept_friend_path(f.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-success' %>
          <%= button_to 'reject', destroy_friendship_path(f.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-danger' %>
        </div>
      </div>  
    </div>
  <% end %>
  <% current_user.pending_invite_friends.uniq.each do |f| %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(f) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(f.email, size: 64, alt: f.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= f.name %>
        </p>
      </div>
      <% end %>  
      <div class='card-footer'>
        <div class='card-footer-item'>
          <button class='button is-static'>invited</button>
        </div>
      </div>    
    <% end %>
  <% end %>
</aside>  

app/views/users/_prefriend.html.erb
<div class='card px-5 pt-5'>
  <div class='card-header'>
    <p class='card-header-title'>
    you must be friends with <%= @user.name %> to view thier profile.
    </p>
  </div>
  <div class='card-footer'>
    <% if @user.friendships.pending.by_accepter(current_user).first.present? %>
    <div class='card-footer-item'>
        <%= button_to 'accept', accept_friend_path(@user.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-success' %>
        <%= button_to 'reject', destroy_friendship_path(@user.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-danger' %>
    </div>
    <% elsif current_user.friendships.pending.by_accepter(@user).first.present? %>  
    <div class='card-footer-item'>
      <button class='button is-static'>invited</button>
    </div>
    <% else %>
    <div class='card-footer-item'>  
      <%= button_to 'add friend', request_friend_path(@user), method: :post, class: 'button is-info' %>
    </div>  
    <% end %>  
  </div>  
</div>

app/views/users/_profile.html.erb
<% @user.posts.order(created_at: :desc).each do |p| %>
<div id='feed_card' class='card has-background-black has-text-white px-5 pt-5 pb-5'>
  <div class='card-header'>
    <div class="card-image">
      <figure class="image is-64x64">
        <%= gravatar_image_tag(@user.email, size: 64, alt: @user.name ) %>
      </figure>
    </div>
    <p class='card-header-title has-text-white'>
      <%= p.user.email %>
    </p>
     
  </div>  
  <div class='card-content'>
    <p>
      <%= p.body %>
    </p>
    <p class='has-text-primary-light'>
      <%= p.created_at%>
    </p>
  </div>
  <div class='card-footer has-text-success'>
    <div class='card-footer-item'>
    <% if user_signed_in? && current_user.liked_posts.include?(p) %>
      <button class='button is-black'><span class='has-text-danger'>♥</span></button>
    <% else %>
      <%= button_to post_add_like_path(p), method: :post, class: 'button is-black' do %>
        <span class='has-text-danger'>♡</span>
      <% end %>  
    <% end %>
    <p class='has-text-danger'><%= p.post_likes.count %></p>
    </div>
    <div class='card-footer-item'>
      <%= button_to '💬', new_post_comment_path(p), method: :get, class: 'button is-black has-text-success' %>
      <p><%= p.comments.count %></p> 
    </div>
    <div class='card-footer-item'>
      <%= button_to '👁', post_path(p), method: :get, class: 'button is-black has-text-info' %>
      <p class='has-text-info'></p>
    </div>  
  </div>  
</div>
<nav class='level'>
</nav>  
<% end %>

app/views/users/edit.html.erb
<section class='hero is-black is-fullheight'>
    <div class='hero-head'>
      <p class='title'>edit profile</p>
    </div>
    <div class='hero-body'>
      <div class='section'>
        <div class='container'>
          <div class='columns is-centered'>
            <div class='column'>
      
              <%= render 'form' %>
            </div>
          </div>
        </div>
    </div>
</section>
  

app/views/users/friends_index.html.erb
<div class='level'>
</div>
<div class='card has-background-primary-light'>
  <div class='card-header'>
    <p class='card-header-title'>
      <%= @user.name %>'s friends
    </p>  
  </div>
</div>
<div class='level'>
</div>
<div class='columns is-multiline'>
  <% @friends.each do |u| %>
  <div class='column is-one-quarter'>  
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(u) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(u.email, size: 64, alt: u.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= u.name %>
        </p>
      <% end %>
      </div>  
      <div class='card-content'>
        <p><%= u.bio %></p>
      </div>
    </div>
  </div>
  <% end %>
</div> 

app/views/users/index.html.erb
<div class='container'>
    <%= render 'feed'%>
</div>

app/views/users/show.html.erb
<section class='hero is-link px-5' >
  <div class='hero-head'>
    <figure class="image is-128x128">
      <%= gravatar_image_tag(@user.email, size: 128, alt: @user.name ) %>
    </figure>
    <p class='title'>
      <%= @user.name %>
    </p>
    <p class='subtitle'>
      <%= @user.email %>
    </p>
  </div>
</section>
<div class='level'>
</div>
<div class='columns px-2'>
  <% if current_user.feed.include?(@user) %>
  <div class='column is-two-fifths pt-3 px-2'>
    <%= render 'left' %>
  </div>
  <div class='column pt-3 px-2'>
    <%= render 'profile' %>
  </div>
  <% else %>
  <div class='column is-two-fifths pt-3 px-2'>
    <%= render 'prefriend' %>
  </div>
  <% end %>
</div>