config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
                     omniauth_callbacks: 'users/omniauth_callbacks',
                     registrations: 'users/registrations' }
  resources :users
  resources :posts do
    resources :comments
  end   

  get '/users/:user_id/friends', to: 'users#friends_index', as: 'user_friends'
  post 'posts/add_like/:id', to: 'posts#add_like', as: 'post_add_like'
  post 'users/request_friend/:id', to: 'users#request_friend', as: 'request_friend'
  post 'users/accept_friend/:id', to: 'users#accept_friend', as: 'accept_friend'
  post 'friendships/destroy/:id', to: 'friendships#destroy', as: 'destroy_friendship'
  post 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :post_likers, :through => :post_likes, :source => :user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if user_signed_in?
      @posts = Post.where(user_id: current_user.feed).order( 'created_at DESC' )
      @post = Post.new
    else
      @posts = []   
    end    
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    @post.save
    redirect_to root_path
  end

  def add_like
    @post = Post.find(params[:id])
    @like = @post.post_likes.build
    @like.user_id = current_user.id
    @like.save
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed.html.erb
<% @posts.each do |p| %>
<div class='card has-background-black has-text-white px-5 pt-5 pb-5'>
  <%= link_to user_path(p.user) do %>
  <div class='card-header'>
    
    <div class="card-image">
      <figure class="image is-64x64">
        <%= gravatar_image_tag(p.user.email, size: 64, alt: p.user.name ) %> 
      </figure>
    </div>
    <p class='card-header-title has-text-white'>
      <%= p.user.name %>
    </p>
    
  </div>
  <% end %>   
  <div class='card-content'>
    <p>
      <%= p.body %>
    </p>
    <p class='has-text-primary-light'>
      <%= p.created_at%>
    </p>
  </div>
  <div class='card-footer has-text-success'>
    <div class='card-footer-item'>
    <% if user_signed_in? && current_user.liked_posts.include?(p) %>
      <button class='button is-black'><span class='has-text-danger'>♥</span></button>
    <% else %>
      <%= button_to post_add_like_path(p), method: :post, class: 'button is-black' do %>
        <span class='has-text-danger'>♡</span>
      <% end %>  
    <% end %>
    <p class='has-text-danger'><%= p.post_likes.count %></p>
    </div>
    <div class='card-footer-item'>
      <%= button_to '💬', new_post_comment_path(p), method: :get, class: 'button is-black has-text-success' %>
      <p><%= p.comments.count %></p> 
    </div>
    <div class='card-footer-item'>
      <%= button_to '👁', post_path(p), method: :get, class: 'button is-black has-text-info' %>
      <p class='has-text-info'></p>
    </div>  
  </div>  
</div>
<nav class='level'>
</nav>  
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
    <div class='field'>
      <div class='control'>
        <%= f.input :body, label: 'new post', input_html: {class: 'textarea '},
                    wrapper: false, label_html: {class: 'label'},
                    placeholder: 'type your post here...' %>
      </div>
    </div>
    <%= f.button :submit, class: 'button is-info' %> 
<% end %>       

app/views/posts/_left.html.erb
<% if user_signed_in? %>  
  <aside class='menu has-background-black has-text-white'>
    <p class='menu-label'>
    where would you like to go
    </p>
    <ul class='menu-list has-text-success'>
      <li><%= link_to 'find friends', users_path, class: 'has-text-success' %></li>
      <li><%= link_to 'view my profile', user_path(current_user), class: 'has-text-success' %></li>
      <li><%= link_to 'see my friends', user_friends_path(current_user), class: 'has-text-success' %></li>
      <li><%= link_to 'edit my profile', edit_user_path(current_user), class: 'has-text-success' %></li>
    </ul>
  </aside>  
<% end %>    

app/views/posts/_right.html.erb
<% if user_signed_in? %>
<aside class='menu has-background-black has-text-white'>
  <p class='menu-label'>pending friend requests
  </p>
  <% if current_user.pending_invite_friends.empty? && current_user.pending_accept_friends.empty? %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
        <p class='card-header-title'>
        no new friend requests
        </p>
      </div>
    </div>    
  <% end %>
  <% current_user.pending_accept_friends.uniq.each do |f| %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(f) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(f.email, size: 64, alt: f.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= f.name %>
        </p>
      </div>
      <% end %>  
      <div class='card-footer'>
        <div class='card-footer-item'>
          <%= button_to 'accept', accept_friend_path(f.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-success' %>
          <%= button_to 'reject', destroy_friendship_path(f.friendships.pending.by_accepter(current_user).first), method: :post, class: 'button is-danger' %>
        </div>
      </div>  
    </div>
  <% end %>
  <% current_user.pending_invite_friends.uniq.each do |f| %>
    <div class='card has-background-black has-text-white'>
      <div class='card-header'>
      <%= link_to user_path(f) do %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(f.email, size: 64, alt: f.name ) %>
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= f.name %>
        </p>
      </div>
      <% end %>  
      <div class='card-footer'>
        <div class='card-footer-item'>
          <button class='button is-static'>invited</button>
        </div>
      </div>    
    <% end %>
  <% end %>
</aside>  

app/views/posts/index.html.erb
<div class='columns px-5 pt-5'>
  <div class='column'>
    <%= render 'left' %>
  </div>
  <% if user_signed_in? %>
  <div class='column is-three-fifths'>
    <div class='card has-background-black has-text-success'>
      <div class='card-header'>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name ) %> 
          </figure>
        </div>
        <p class='card-header-title has-text-white'>
          <%= current_user.name %>'s feed
        </p>
      </div>
    </div>
    <%= render 'form' %>
    <div class='level'>
    <% end %>
    </div>  
    <%= render 'feed' %>
  </div>
  <div class='column'>
    <%= render 'right' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class='level'>
</div>
<article class="media has-background-black has-text-white px-5 pt-5">
  <%= link_to user_path(@post.user) do %>
  <figure class="media-left">
    <p class="image is-64x64">
      <%= gravatar_image_tag(@post.user.email, size: 64, alt: @post.user.name ) %>
    </p>
  </figure>
  <% end %>
  <div class="media-content">
    <div class="content">
      <p class='is-success'>
        <strong><%= @post.user.name%></strong>
        <br>
        <%= @post.body %>
        <br>
        <div class='card has-background-black'>
        <div class='card-footer'>
        <div class='card-footer-item'>
        <% if user_signed_in? && current_user.liked_posts.include?(@post) %>
          <button class='button is-black'><span class='has-text-danger'>♥</span></button>
        <% else %>
        <%= button_to post_add_like_path(@post), method: :post, class: 'button is-black' do %>
          <span class='has-text-danger'>♡</span>
          <% end %>  
        <% end %>
          <p class='has-text-danger'>likes: <%= @post.post_likes.count %></p>
        </div>
        <div class='card-footer-item'>
          <%= button_to '💬', new_post_comment_path(@post), method: :get, class: 'button is-black has-text-success' %>
          <p class='has-text-success'>comments: <%= @post.comments.count %></p>
        </div>
        <% if @post.user == current_user %>
        <div class='card-footer-item' >
          <%= button_to '🗑', destroy_post_path(@post), method: :post, class: 'button is-black has-text-link' %>
        </div>
        <% end %>
        </div>
        </div>
      </p>
    </div>
    <% @post.comments.each do |c|%>
    <article class="media has-background-black has-text-white px-5 pt-5">
      <%= link_to user_path(c.user) do %>
      <figure class="media-left">
        <p class="image is-48x48">
          <%= gravatar_image_tag(c.user.email, size: 64, alt: c.user.name ) %>
        </p>
      </figure>
      <% end %>
      <div class="media-content">
        <div class="content">
          <p>
            <strong class='is-success'><%= c.user.name%></strong>
            <br>
            <%= c.body %>
            <br>
          </p>
        </div>
      </div>  
    </article>
    <% end %>
  </div>
</article>      