config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
                     omniauth_callbacks: 'users/omniauth_callbacks',
                     registrations: 'users/registrations' }
  resources :users
  resources :posts do
    resources :comments
  end   

  get '/users/:user_id/friends', to: 'users#friends_index', as: 'user_friends'
  post 'posts/add_like/:id', to: 'posts#add_like', as: 'post_add_like'
  post 'users/request_friend/:id', to: 'users#request_friend', as: 'request_friend'
  post 'users/accept_friend/:id', to: 'users#accept_friend', as: 'accept_friend'
  post 'friendships/destroy/:id', to: 'friendships#destroy', as: 'destroy_friendship'
  post 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  attr_accessor :inviting_friend_id, :accepting_friend_id

  belongs_to :inviter, :class_name => 'User', :foreign_key => :inviting_friend_id
  belongs_to :accepter, :class_name => 'User', :foreign_key => :accepting_friend_id
  
  scope :pending, -> { where(status: 'pending') }
  scope :accepted, -> { where(status: 'accepted') }
  scope :by_inviter, ->(user) { where(inviter: user) }
  scope :by_accepter, ->(user) { where(accepter: user) }
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :post_likers, :through => :post_likes, :source => :user

end

app/models/post_like.rb
class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord

  
  has_many :posts
  has_many :comments
  has_many :post_likes
  has_many :liked_posts, :through => :post_likes, :source => :post
  has_many :friendships, :foreign_key => :accepting_friend_id
  has_many :friendships, :foreign_key => :inviting_friend_id 

  has_and_belongs_to_many :invited_friends,
                class_name: 'User',
                join_table: :friendships,
                foreign_key: :inviting_friend_id,
                association_foreign_key: :accepting_friend_id


  has_and_belongs_to_many :accepted_friends,
                class_name: 'User',
                join_table: :friendships,
                foreign_key: :accepting_friend_id,
                association_foreign_key: :inviting_friend_id              
  
                 
  def pending_invite_friends
    (invited_friends.joins(:friendships).merge(Friendship.pending))
  end

  def confirmed_invite_friends
    (invited_friends.joins(:friendships).merge(Friendship.accepted))
  end

  def pending_accept_friends
    (accepted_friends.joins(:friendships).merge(Friendship.pending))
  end

  def confirmed_accept_friends
    (accepted_friends.joins(:friendships).merge(Friendship.accepted))
  end

  def friends
    (confirmed_invite_friends + confirmed_accept_friends).flatten.uniq
  end

  def feed
    (self.friends << self)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new

  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.save
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.save
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
  end


  private

  def friendship_params
    params.require(:friendship).permit(:inviting_friend_id, :accepting_friend_id, :status)
  end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController

  def new
    @post_like = PostLike.new
  end

  def create
    @post_like = PostLike.new(post_like_params)
    @post_like.save
    redirect_to root_path 
  end

  private 

  def post_like_params
    params.require(:post_like).permit(:post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if user_signed_in?
      @posts = Post.where(user_id: current_user.feed).order( 'created_at DESC' )
      @post = Post.new
    else
      @posts = []   
    end    
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    @post.save
    redirect_to root_path
  end

  def add_like
    @post = Post.find(params[:id])
    @like = @post.post_likes.build
    @like.user_id = current_user.id
    @like.save
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
    @user = User.find(params[:id])
  end

  def index
    @search = params['search']
    if @search.present?
      @users = User.where('name = ?', @search['name'])
    else
      @users = (User.all.excluding(current_user.friends, current_user))
    end
  end

  def friends_index
    @user = User.find(params[:user_id])
    @friends = @user.friends 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update((user_params))
    redirect_to user_path(@user)
  end

  def request_friend
    @friend = User.find(params[:id])
    @request = Friendship.new
    @request.status = 'pending'
    @request.inviter = current_user
    @request.accepter = @friend
    @request.save
    redirect_to root_path
  end

  def accept_friend
    @request = Friendship.find(params[:id])
    @request.status = 'accepted'
    @request.save
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :location, :birthday, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_splash.html.erb
  <section class='hero is-black is-fullheight'>
    <div class='hero-head'>
      <p class='title'>facelord</p>
    </div>
    <div class='hero-body'>
      <div class='section'>
      <div class='container'>
      <div class='columns is-centered'>
      <div class='column is-4'>
      <h4 class='title is-2'>Log in</h4>
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class='field'>
            <div class='control'>
            <%= f.input :email,
                        required: true,
                        autofocus: true,
                        input_html: { class: 'input' },
                        wrapper: false,
                        label: false,
                        placeholder: 'email' %>
                        
            </div>
          </div>    
          <div class='field'>
            <div class='control'>
            <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { class: 'input' },
                        wrapper: false,
                        label: false,
                        placeholder: 'password'  %>
            </div>
          </div>  
          <div class='field'>
            <%= f.input :remember_me, class: 'checkbox is-black', as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class='field is-horizontal'>
            <div class='control'>  
            <%= f.button :submit, "log in", class: 'button is-primary' %>
            </div>
        <% end %>
            <div class='control'>
            <%= button_to 'sign up', new_user_registration_path, method: :get, class: 'button is-white has_text-priimary' %>
            </div>
        </div>
        <div class='level has-background-black has-text-centered has-text-white pt-5'>
          <p>- or -</p>
        </div>  
        <div class='field'>
          <div class='control'>
          <%= button_to 'sign in with facebook', user_facebook_omniauth_authorize_path, class: 'button is-info' %>
          </div>
        </div>
        </div>
      </div>
    </div>
    </div>
  </section>
  

app/views/layouts/_standard.html.erb
<section class='hero is-primary is-medium'>
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <p class='title'>
            <%= link_to 'facelord', root_path %>
          </p>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to 'logout', destroy_user_session_path, class: 'navbar-item' %>
            <% if user_signed_in? %>
              <%= link_to 'my profile', user_path(current_user), class: 'navbar-item' %>
            <% end %>  
            <%= link_to 'new post', new_post_path, class: 'navbar-item' %>
            <a class="navbar-item">
              <div class='icon-text'>
                <span class='icon has-text-success'><i class="fa-thin fa-square-up-right" aria-hidden='true' ></i></span>
              </div>  
            </a>
          </div>
        </div>  
      </div>
    </nav>
  </div>      
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='has-text-white has-background-dark'>
  <head>
    <title>Facelord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
  <% if user_signed_in? || current_page?(controller: 'users/registrations', action: 'new') %>
    <%= render 'layouts/standard' %>
  <div class='container'>
    <%= yield %>
  </div>
  <% else %>
    <%= render 'layouts/splash' %>  
  <% end %>    
  </body>
</html>